home/urls.py
from django.conf.urls import include,url
from . import views

app_name='home'

urlpatterns=[
	url(r'^$',views.home,name='home'),
]

price/urls.py
from django.conf.urls import include,url
from . import views

app_name='price'

urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^register/$', views.register, name='register'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
	url(r'^buy/(?P<company_symbol>[A-Z]+)/(?P<price>\d+\.\d{1,2})/$', views.buy, name='buy'),
	url(r'^sell/(?P<cs>[A-Z]+)/(?P<price>\d+\.\d{1,2})/$', views.sell, name='sell'),
	url(r'^(?P<company_symbol>[A-Z]+)/',views.detail,name='detail'),
]

vsm/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^$',include('home.urls')),
     url(r'^price/', include('price.urls')),
    url(r'^admin/', admin.site.urls)
    
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

def home(request):
	if request.user.is_authenticated():
		return render(request, 'price/home2.html')
	else:
		return render(request, 'price/home3.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Vsm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'styl.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="bower_components/moment/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body style="background-color:#eee">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-image" href="#"><span class="logo">Virtual Stock Market</span></a>
        </div>
        <!--as above part is not under collapse it will remain as it is even after reducing screen size-->

        <!--link the below section under collapse with id to the above defined button-->
        <div class="collapse navbar-collapse options" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'home:home'%}">Home</a></li>
				
                <!--<li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">HELLO {{name}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">National</a></li>
                        <li><a href="#">International</a></li>
                        <li><a href="#">Conducted</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Customised</a></li>
                    </ul>
                </li>-->
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'price:register'%}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="{% url 'price:login_user'%}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>


    </div>
</nav>




{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% block albums_active %}active{% endblock %}
{% block body %}
{% load staticfiles %}
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>

    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">

            <img src="{%  static 'welcome.jpg' %}" alt="cpg" class="img-responsive" style="width:1400px;height:500px;">
            
            </div>
        <div class="item">
            <img src="{%  static 'building.jpe' %}" alt="lol" class="img-responsive" style="width:1400px;height:500px;">
            <!--<div class="carousel-caption">
                <h3>New Offers are awaiting!!</h3>
            </div>-->
        </div>

    </div>

    <!-- Control arrows of image slider-->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="row middle">
    <div class="col-md-3 update">
        <p class="blogs"><a href="#">Blogs</a></p>
    </div>
    <div class="col-md-6 query">
        <p>For any queries feel free to contact us......</p>
    </div>
    <div class="col-md-3 update1">
        <p class="blog1"><a href="#">Customer Support</a></p>
    </div>
</div>


<div class="space"></div>
<p class="trend">Online Courses:</p>
<div class="container lined-images">
    <div class="row">
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'cema.jpg' %}" alt="eiffel-tower" class="img-responsive center-block">
                </div>
            <div class="col-md-4">
                <h5 class="title">CEMA:</h5>
                <p class="small">The main aim of the programme is to develop domain knowledge
expertise in...</p>
                <p class="al_right"><a href="https://www.ncfm-india.com/ORE/ORECEMARegistrationNew.jsp">More..</a></p>
            </div>
        </div>
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'crta.jpg' %}" alt="bali" class="img-responsive center-block">
            </div>
            <div class="col-md-4">
                <h5 class="title">CRTA:</h5>
                <p class="small">You will get to learn share market basics,market research,mathematical modelling...</p>
                <p class="al_right"><a href="https://www.elearnmarkets.com/nse">More..</a></p>
            </div>
        </div>
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'ncfm.png' %}" alt="london" class="img-responsive center-block">
            </div>
            <div class="col-md-4 ">
                <h5 class="title">NCFM:</h5>
                <p class="small">NCFM is a nationally recognized certification which is mandatory for </p>
                <p class="al_right"><a href="https://www.nseindia.com/education/content/module_ncfm.htm">More..</a></p>

            </div>
        </div>
    </div>
</div>

<div class="space"></div>


<div class="space"></div>
<div class="container head">
    <div class="row">
        <div class="col-md-12">
            <h3>Stock Talk:</h3>
        </div>
    </div>
</div>

<div class="container lined-images">
    <div class="row">
        <div class="col-md-6 bottom">
            <h4 align="center">Swami Lilashah Aarti:</h4>
            <!--embedding video using bootstrap-->
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" width="460" height="200" src="https://www.youtube.com/embed/lzndqHovfbM" alt="aarti" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
		<div class="col-md-6 bottom">
            <h4 align="center">Vaishnodevi maa:</h4>
            <!--embedding video using bootstrap-->
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" width="460" height="150" src="https://www.youtube.com/embed/1JJJsh6Ge0M" alt="aarti" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
<div class="space"></div>
<div class="container head">
<div class="row">
    <div class="col-md-12">
        <h3>Explore some companies !!!!</h3>
    </div>
    </div>
    </div>
<div class="space"></div>
<div class="container">
    <div class="row">
        <div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'wipro.jpe' %}" alt="swami_lilashah" class="img-responsive center-block" padding-top:20px>
                <div class="caption">
                    <h3>WIPRO</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'WPRO'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		<div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'nestle.png' %}" alt="swami_lilashah" class="img-responsive center-block" >
                <div class="caption">
                    <h3>NESTLE</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'NEST'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		
        
        <div class="col-md-4 sn-4">
            <div class="thumbnail">
                <img src="{%  static 'sbi.png' %}" alt="vaishnodevi" class="img-responsive center-block">
                <div class="caption">
                    <h3>SBI Bank</h3>
                    <!--<p>Jai Mata Di !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'SBIN'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		</div>
		</div>
		<div class="container">
		<div class="row">
        <div class="col-md-4 sn-4 bala">
            <div class="thumbnail">
                <img src="{%  static 'lt.png' %}" alt="balaji" class="img-responsive center-block" padding-top:20px>
                <div class="caption">
                    <h3>L&T</h3>
                    <!--<p>Jai Shri Krishna !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'LT'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		<div class="col-md-4 sn-4">
            <div class="thumbnail">
                <img src="{%  static 'icici.png' %}" alt="golden_temple" class="img-responsive center-block">
                <div class="caption">
                    <h3>ICICI Bank</h3>
                    <!--<p>Satnam Waheguruji !!!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'ICICIBC'%}">Learn More</a></button>
                </div>
            </div>
        </div>
        
        
		<div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'reliance.png' %}" alt="swami_lilashah" class="img-responsive center-block">
                <div class="caption">
                    <h3>RELIANCE</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'RIL'%}">Learn More</a></button>
                </div>
            </div>
			</div>
        </div>
    </div>
	</div>
</div>
<div class="space"></div>
<div class="container head">
    <div class="row">
        <div class="col-md-12 why">
            <h3>Why Travel With Us When There Are So Many Around ?? <button type="button" class="btn btn-warning" align="right">Find out...</button> </h3>
        </div>
    </div>
</div>
<div class="space"></div>

    

{% endblock %}