home/urls.py
from django.conf.urls import include,url
from . import views

app_name='home'

urlpatterns=[
	url(r'^$',views.home,name='home'),
]

price/urls.py
from django.conf.urls import include,url
from . import views

app_name='price'

urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^register/$', views.register, name='register'),
	url(r'^about/$', views.about, name='about'),
	url(r'^contact/$', views.contact, name='contact'),
	url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
	url(r'^buy/(?P<company_symbol>[A-Z]+)/(?P<price>\d+\.\d{1,2})/$', views.buy, name='buy'),
	url(r'^sell/(?P<cs>[A-Z]+)/(?P<price>\d+\.\d{1,2})/$', views.sell, name='sell'),
	url(r'^(?P<company_symbol>[A-Z]+)/',views.detail,name='detail'),
]

vsm/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'^$',include('home.urls')),
     url(r'^price/', include('price.urls')),
    url(r'^admin/', admin.site.urls)
    
]

home/models.py
from django.db import models

# Create your models here.

price/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.utils import timezone

class Transaction(models.Model):
	user = models.ForeignKey(User)
	transact_date = models.DateTimeField(default=timezone.now)
	virtual_cash=models.FloatField(default=0.0)
	company_symbol = models.CharField(max_length=250)
	purchase_rate = models.FloatField(default=0.0)
	purchase_quantity = models.PositiveSmallIntegerField(default=0)
	purchase_amount = models.FloatField(default=0.0)
	sale_rate = models.FloatField(default=0.0)
	sale_quantity = models.PositiveSmallIntegerField(default=0)
	sale_amount = models.FloatField(default=0.0)
	profit = models.FloatField(default=0.0)
	balance_shares=models.IntegerField(default=0)
	
	

	def __str__(self):
		return str(self.user) + ' - ' + self.company_symbol
		
class UserInfo(models.Model):
	#user=models.IntegerField(default=0)
	user = models.ForeignKey(User)
	virtual_cash=models.FloatField(default=0.0)
	
	def __str__(self):
		return str(self.user) + ' - ' + str(self.virtual_cash)
		
class Portfolio(models.Model):
	user = models.ForeignKey(User)
	c_name=models.CharField(max_length=250)
	bought_shares=models.IntegerField(default=0)
	sold_shares=models.IntegerField(default=0)
	bal_shares=models.IntegerField(default=0)
	current_market_price=models.FloatField(default=0.0)
	market_evaluation=models.FloatField(default=0.0)
	profit=models.FloatField(default=0.0)
	profit_on_transact=models.FloatField(default=0.0)
	profit_on_current=models.FloatField(default=0.0)
	
	def __str__(self):
		return str(self.user) + ' - ' + str(self.profit)
	
	

price/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Transaction

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class BuyForm(forms.ModelForm):

	class Meta:
		model= Transaction
		fields=['purchase_quantity']
		
class SellForm(forms.ModelForm):

	class Meta:
		model= Transaction
		fields=['sale_quantity']

		

home/views.py
from django.shortcuts import render

def home(request):
	if request.user.is_authenticated():
		return render(request, 'price/home2.html')
	else:
		return render(request, 'price/home3.html')

price/views.py
from django.shortcuts import render,get_object_or_404,redirect
import urllib.request
import re
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import UserForm,BuyForm,SellForm
from .models import Transaction,UserInfo,Portfolio
import math
import json

app_name='price'

'''def portfolio(request):
	if not request.user.is_authenticated():
		return render(request, 'price/login.html')
	else:
		display=[]
		company = ["GOOG","AAPL","RELIANCE","ICICIBANK","HCLTECH","WIPRO"]
		for cs in company:
			d=[]
			for t in Transaction.objects.filter(user=request.user,company_symbol=cs):
				purchase_quantity=0
				if t.sale_amount == 0:
					purchase_quantity=t.purchase_amount/t.purchase_rate
					
					
		return render(request,'price/portfolio.html',{'transact':transact})'''
def contact(request):
	return render(request,'price/contact.html')
	
def about(request):
	return render(request,'price/about.html')

	
def portfolio(request):
	if not request.user.is_authenticated():
		return render(request, 'price/login.html')
	else:
		display=[]
		company = ["WPRO","NEST","SBIN","ICICIBC","RIL","LT"]
		
		user_info = UserInfo.objects.get(user=request.user)
		sp=0
		pt=0
		bs=0
		p=0
		for c in company:
			pf=Portfolio.objects.get(user=request.user,c_name=c)
			
			pf.bal_shares=pf.bought_shares-pf.sold_shares
			if pf.bal_shares or pf.bought_shares:
				bs+=pf.bought_shares
				user_info = Transaction.objects.get(user=request.user,company_symbol=c,balance_shares=pf.bal_shares)
				prate=user_info.purchase_rate
				cp=prate*pf.bal_shares
				
				htmltext1 = urllib.request.urlopen("https://www.bloomberg.com/markets/api/bulk-time-series/price/"+c+":IN?timeFrame=1_DAY");	
				data = json.load(htmltext1)
				price = float(data[0]['lastPrice'])
				pf.current_market_price=price
				pf.market_evaluation=price*pf.bal_shares
				pf.profit_on_transact=user_info.profit
				p+=pf.profit_on_transact
				pf.profit_on_current=pf.market_evaluation-cp
				pt=pt+pf.profit_on_current
				sp+=pf.market_evaluation
				display.append(pf)
				pf.save()
		e=0
		if sp==0 and bs==0:
			e=1
		sp=round(sp,2)
		vc=round(user_info.virtual_cash,2)
		
		
		net_profit=round(pt,2)
		name=request.user.username
		context={ "display":display , "net_profit":net_profit, "vc":vc , "name":name ,"e":e,"p":p}
		return render(request,'price/portfolio.html',context)

		
			
			
		
	
	
def index(request):
	company = ["WPRO","NEST","SBIN","ICICIBC","RIL","LT"]
	context = {
					"company": company,
				}
	return render(request, 'price/index.html', context)
	
def detail(request,company_symbol):
		if not request.user.is_authenticated():
			return render(request, 'price/login.html')
		else:
			htmltext1 = urllib.request.urlopen("https://www.bloomberg.com/markets/api/bulk-time-series/price/"+company_symbol+":IN?timeFrame=1_DAY");	
			data = json.load(htmltext1)

			mylist=[]
			t=len(data[0]['price'])

			for i in range(0,t):
				mylist.append(data[0]['price'][i]['value'])

			price = float(data[0]['lastPrice'])
			mylist.append(price)
			t=t+1
			diff=round(price-data[0]['price'][t-2]['value'],2)
			if diff >=0:
				progress=1
			else:
				progress=0
			name=request.user.username
			context={ "price":price , "company_symbol":company_symbol , "mylist":mylist , "t":t,"progress":progress,"diff":diff,"name":name
			}
			return render(request,'price/detail.html',context)
			
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'price/home3.html', context)


def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				visit=0
				context = { "visit":visit
				}
				return render(request, 'price/home2.html', context)
			else:
				return render(request, 'price/login.html', {'error_message': 'Your account has been disabled'})
		else:   
			return render(request, 'price/login.html', {'error_message': 'Invalid login'})
	return render(request, 'price/login.html')


def register(request):
	form = UserForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		user.set_password(password)
		user.save()
		new_user=UserInfo()
		new_user.user=user
		new_user.virtual_cash=50000.0
		#user.save()
		new_user.save()
		company = ["WPRO","NEST","SBIN","ICICIBC","RIL","LT"]
		for c in company:
			pf=Portfolio()
			pf.user=user
			pf.c_name=c
			pf.save()
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return render(request, 'price/home2.html', {'company':company})
                
	context = {
        "form": form,
               }
	return render(request, 'price/register.html', context)
	
def buy(request,company_symbol,price):
	if not request.user.is_authenticated():
		return render(request, 'price/login.html')
	else:
		#transact = get_object_or_404(Transaction, pk=request.user.id)
		if request.method=="POST":
			form = BuyForm(request.POST)
			if form.is_valid():
				try:
					#transact = get_object_or_404(Transaction, pk=request.user.id)
					pkey=request.user.id
					transact = form.save(commit=False)
					purchase_quantity = int(form.cleaned_data['purchase_quantity'])
					price=float(price)
					user_info = UserInfo.objects.get(user=request.user)
					if user_info.virtual_cash<(price*purchase_quantity):
						return render(request, 'price/buy.html', {'error_message': "You don't have enough virtual cash to buy the shares"})
					elif purchase_quantity == 0:
						return render(request, 'price/buy.html', {'error_message': "Please enter non zero purchase quantity"})				
					else:
						pf=Portfolio.objects.get(user=request.user,c_name=company_symbol)
						pf.bought_shares+=purchase_quantity
						pf.save()
						
						
						transact.user=user_info.user
						user_info.virtual_cash-=price*purchase_quantity
						transact.virtual_cash=round(user_info.virtual_cash,2)
						user_info.save()
						transact.company_symbol=company_symbol
						transact.purchase_rate = price
						transact.balance_shares+=purchase_quantity
					
						#transact.purchase_quantity = quantity
						transact.purchase_amount = price*purchase_quantity
						transact.save()
						
				except Transaction.DoesNotExist:
					return render(request, 'price/buy.html', {'error_message': "Error in retreiving transaction table"})
				return render(request,'price/status.html',{'transact':transact})
		else:
			form = BuyForm()
			return render(request, 'price/buy.html', {'form': form})
			
				
		
def sell(request,cs,price):
	if not request.user.is_authenticated():
		return render(request, 'price/login.html')
	else:
		if request.method=="POST":
			form = SellForm(request.POST)
			if form.is_valid():
				try:
					sale_quantity = int(form.cleaned_data['sale_quantity'])
					transacts = []
					q=0
					purchase_amount=0
					#primary=Transaction.objects.filter(user=request.user)
					
					for t in Transaction.objects.filter(user=request.user,company_symbol=cs,sale_amount=0.0):
						if t.purchase_quantity>0:
							purchase_amount+=t.purchase_rate*t.purchase_quantity
							q+=t.purchase_quantity
							transacts.append(t)
					
					transact=Transaction()
					transact.user=request.user
					if not q>=sale_quantity and sale_quantity>0:
						return render(request, 'price/sell.html', {'error_message': "You don't have shares of this company"})
					elif sale_quantity == 0:
						return render(request, 'price/sell.html', {'error_message': "Please enter non zero sell quantity"})				
					else:
						pf=Portfolio.objects.get(user=request.user,c_name=cs)
						pf.sold_shares+=sale_quantity
						
						
						price=float(price)
						user_info = UserInfo.objects.get(user=request.user)
						transact.purchase_rate=purchase_amount/q
						transact.purchase_rate=round(transact.purchase_rate,2)
						pr=purchase_amount/q
						transact.purchase_amount=(transact.purchase_rate)*q
						
						transact.company_symbol=cs
						transact.purchase_quantity=q
						#transact.virtual_cash+=price*quantity
						transact.sale_rate = price
						transact.sale_quantity = sale_quantity
						transact.sale_amount = price*sale_quantity
						transact.balance_shares=q-sale_quantity
						vc=user_info.virtual_cash
						transact.virtual_cash=round(vc+price*sale_quantity,2)
						user_info.virtual_cash=transact.virtual_cash
						transact.profit=round(price*sale_quantity-pr*sale_quantity,2)
						pf.profit_on_transact+=transact.profit
						pf.save()
						transact.save()
						user_info.save()
						context={'transact':transact
						}
						
						for t in transacts:
							if sale_quantity:
								if t.purchase_quantity>sale_quantity:
									t.purchase_quantity-=sale_quantity
									sale_quantity=0
									t.save()
								else:
									t.purchase_quantity=0
									sale_quantity-=1
									t.save()
								
				except Transaction.DoesNotExist:
					return render(request, 'price/sell.html', {'error_message': "Error in retreiving transaction table"})
				return render(request, 'price/status.html', context)
		else:
			form = SellForm()
			return render(request, 'price/sell.html', {'form': form})
		

price/templates/price/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Vsm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'styl.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="bower_components/moment/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body style="background-color:#eee">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-image" href="#"><span class="logo">Virtual Stock Market</span></a>
        </div>
        <!--as above part is not under collapse it will remain as it is even after reducing screen size-->

        <!--link the below section under collapse with id to the above defined button-->
        <div class="collapse navbar-collapse options" id="myNavbar">
            <ul class="nav navbar-nav">
			
			<li class="dropdown">
			
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">HELLO {{name}} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'price:logout_user'%}">Logout</a></li>
                        
                    </ul>
                </li>
				<li><a href="{% url 'price:portfolio'%}">Portfolio</a></li>
				<li><a href="{% url 'home:home'%}">Home</a></li>
			
					
                    
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            
        </div>


    </div>
</nav>




{% block body %}
{% endblock %}
</body>
</html>

price/templates/price/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Vsm{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'styl.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="bower_components/moment/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body style="background-color:#eee">
<nav class="navbar navbar-inverse ">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand-image" href="#"><span class="logo">Virtual Stock Market</span></a>
        </div>
        <!--as above part is not under collapse it will remain as it is even after reducing screen size-->

        <!--link the below section under collapse with id to the above defined button-->
        <div class="collapse navbar-collapse options" id="myNavbar">
            <ul class="nav navbar-nav">
			
			
				<li><a href="{% url 'price:portfolio'%}">Portfolio</a></li>
				<li><a href="{% url 'home:home'%}">Home</a></li>
			
					
                    
                <li><a href="{% url 'price:about'%}">About</a></li>
                <li><a href="{% url 'price:contact'%}">Contact</a></li>
            </ul>
            
        </div>


    </div>
</nav>




{% block body %}
{% endblock %}
<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
            
            
            <a class="navbar-brand cr" href="#"><span class="cr">&#169 copyrights reserved</span></a>
        </div>

</div>
</nav>
</body>
</html>

price/templates/price/detail.html
{% extends 'price/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
	{% if progress %}
		<h1>{{company_symbol}}  {{price}}(INR) <span class="glyphicon glyphicon-arrow-up" style="color:green"></span> <font style="color:green">{{diff}}</font></h1>
	{% else %}
		<h1>{{company_symbol}} {{price}} (INR) <span class="glyphicon glyphicon-arrow-down" style="color:red"></span> <font style="color:red"> {{diff}}</font></h1>
	{% endif %}
<ul>
	<li><a href="{% url 'price:buy' company_symbol=company_symbol price=price%}">Buy</a></li>
	<li><a href="{% url 'price:sell' cs=company_symbol price=price%}">Sell</a></li>
</ul>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<canvas id="myChart" height="400" width="800"></canvas> 

<script>

var ctx = document.getElementById("myChart").getContext('2d');
var time = []
var x=15
var y=9

var t={{t}}
for(i=0;i<t;i++){
	
	time.push(y.toString()+":"+x.toString());

	if (x==55){
		y=y+1;
		x=0;
	}
	else
		x=x+5;	
}
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: time,
        datasets: [{
            label: "Stock value",
            data: {{mylist}},
            backgroundColor: [
                
                'rgba(255, 159, 124, 0.8)'
            ],
            
            borderWidth: 1
        }]
    },
    options: {
        responsive: false,
        scales: {


            yAxes: [{
                ticks: {
                    beginAtZero:false
                }
            }]
        }
    }
});

</script>

{% endblock %}

price/templates/price/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

price/templates/price/home3.html
{% extends 'price/base_home.html' %}
{% block albums_active %}active{% endblock %}
{% block body %}
{% load staticfiles %}
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>

    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">

            <img src="{%  static 'welcome.jpg' %}" alt="cpg" class="img-responsive" style="width:1400px;height:500px;">
            
            </div>
        <div class="item">
            <img src="{%  static 'building.jpe' %}" alt="lol" class="img-responsive" style="width:1400px;height:500px;">
            <!--<div class="carousel-caption">
                <h3>New Offers are awaiting!!</h3>
            </div>-->
        </div>

    </div>

    <!-- Control arrows of image slider-->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="row middle">
    <div class="col-md-3 update">
        <p class="blogs"><a href="#">Don't</a></p>
    </div>
    <div class="col-md-6 query">
        <p>For any queries feel free to contact us......</p>
    </div>
    <div class="col-md-3 update1">
        <p class="blog1"><a href="#">Hesitate</a></p>
    </div>
</div>


<div class="space"></div>
<p class="trend">Online Courses:</p>
<div class="container lined-images">
    <div class="row">
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'cema.jpg' %}" alt="eiffel-tower" class="img-responsive center-block">
                </div>
            <div class="col-md-4">
                <h5 class="title">CEMA:</h5>
                <p class="small">The main aim of the programme is to develop domain knowledge
expertise in...</p>
                <p class="al_right"><a href="https://www.ncfm-india.com/ORE/ORECEMARegistrationNew.jsp">More..</a></p>
            </div>
        </div>
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'crta.jpg' %}" alt="bali" class="img-responsive center-block">
            </div>
            <div class="col-md-4">
                <h5 class="title">CRTA:</h5>
                <p class="small">You will get to learn share market basics,market research,mathematical modelling...</p>
                <p class="al_right"><a href="https://www.elearnmarkets.com/nse">More..</a></p>
            </div>
        </div>
        <div class="col-md-4 sn-4">
            <div class="col-md-8">
                <img src="{%  static 'ncfm.png' %}" alt="london" class="img-responsive center-block">
            </div>
            <div class="col-md-4 ">
                <h5 class="title">NCFM:</h5>
                <p class="small">NCFM is a nationally recognized certification which is mandatory for </p>
                <p class="al_right"><a href="https://www.nseindia.com/education/content/module_ncfm.htm">More..</a></p>

            </div>
        </div>
    </div>
</div>

<div class="space"></div>


<div class="space"></div>
<div class="container head">
    <div class="row">
        <div class="col-md-12">
            <h3>Stock Talk:</h3>
        </div>
    </div>
</div>

<div class="container lined-images">
    <div class="row">
        <div class="col-md-6 bottom">
            <h4 align="center">Stock market for beginners:</h4>
            <!--embedding video using bootstrap-->
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" width="460" height="200" src="https://www.youtube.com/embed/0asQOYockjY" alt="begin" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
		<div class="col-md-6 bottom">
            <h4 align="center">Understanding Stock market:</h4>
            <!--embedding video using bootstrap-->
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" width="460" height="150" src="https://www.youtube.com/embed/Fk1INY4gNk0" alt="aarti" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
<div class="space"></div>
<div class="container head">
    <div class="row">
        <div class="col-md-12 why">
            <p class="trend">How To Play Our Game ???                                  <button type="button" class="btn btn-warning" align="right"><a href="{% url 'price:about'%}">Find out...</a></button> </p>
        </div>
    </div>
</div>
<div class="container head">
<div class="row">
    <div class="col-md-12">
        <p class="trend">Explore some companies !!!!</p>
    </div>
    </div>
    </div>
<div class="space"></div>
<div class="container">
    <div class="row">
        <div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'wipro.jpe' %}" alt="swami_lilashah" class="img-responsive center-block" padding-top:20px>
                <div class="caption">
                    <h3>WIPRO</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'WPRO'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		<div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'nestle.png' %}" alt="swami_lilashah" class="img-responsive center-block" >
                <div class="caption">
                    <h3>NESTLE</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'NEST'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		
        
        <div class="col-md-4 sn-4">
            <div class="thumbnail">
                <img src="{%  static 'sbi.png' %}" alt="vaishnodevi" class="img-responsive center-block">
                <div class="caption">
                    <h3>SBI Bank</h3>
                    <!--<p>Jai Mata Di !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'SBIN'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		</div>
		</div>
		<div class="container">
		<div class="row">
        <div class="col-md-4 sn-4 bala">
            <div class="thumbnail">
                <img src="{%  static 'lt.png' %}" alt="balaji" class="img-responsive center-block" padding-top:20px>
                <div class="caption">
                    <h3>L&T</h3>
                    <!--<p>Jai Shri Krishna !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'LT'%}">Learn More</a></button>
                </div>
            </div>
        </div>
		<div class="col-md-4 sn-4">
            <div class="thumbnail">
                <img src="{%  static 'icici.png' %}" alt="golden_temple" class="img-responsive center-block">
                <div class="caption">
                    <h3>ICICI Bank</h3>
                    <!--<p>Satnam Waheguruji !!!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'ICICIBC'%}">Learn More</a></button>
                </div>
            </div>
        </div>
        
        
		<div class="col-md-4 sn-4 ma">
            <div class="thumbnail">
                <img src="{%  static 'reliance.png' %}" alt="swami_lilashah" class="img-responsive center-block">
                <div class="caption">
                    <h3>RELIANCE</h3>
                    <!--<p>Jai Ramji Ki !!!</p>-->
                    <button type="button" class="btn btn-default"><a href="{% url 'price:detail' 'RIL'%}">Learn More</a></button>
                </div>
            </div>
			</div>
        </div>
    </div>
	</div>
</div>
<div class="space"></div>

<div class="space"></div>

    

{% endblock %}

price/templates/price/index.html
{% extends 'price/base.html' %}
{% block albums_active %}active{% endblock %}
{% block body %}
{% if company %}
    <ul>
    {% for i in company %}
        <li><a href="{% url 'price:detail' i%}">{{ i }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No companies are available.</p>
{% endif %}
{% endblock %}